export const QUESTIONS = [
  "What's one small thing you did today that made you happy?",
  "If you could instantly master any skill, what would it be?",
  "What's your favorite childhood memory?",
  "What's one goal you want to achieve this month?",
  "Who inspires you the most and why?",
  "If you could live anywhere in the world, where would it be?",
  "What's the best piece of advice you've ever received?",
  "What's your favorite way to relax?",
  "If you had to eat one food for the rest of your life, what would it be?",
  "What's your biggest accomplishment so far?",
  "What's a habit you’re trying to build?",
  "If you could time travel, where would you go?",
  "What's your dream job?",
  "What’s a book or movie that changed your perspective?",
  "What's your favorite thing to do on weekends?",
  "If you could meet any historical figure, who would it be?",
  "What's a skill you think everyone should learn?",
  "What motivates you on tough days?",
  "What's one fear you want to overcome?",
  "What's your favorite holiday or tradition?",
  "If money wasn't an issue, what would you do all day?",
  "What's the kindest thing someone has done for you?",
  "What's a fun fact about you?",
  "What's a goal you're working towards right now?",
  "If you could instantly travel anywhere, where would you go?",
  "What's your favorite season and why?",
  "What's one thing you wish you learned earlier?",
  "What’s the best compliment you’ve ever received?",
  "What's your favorite childhood game?",
  "If you could relive one day of your life, which would it be?",
  "What's your go-to comfort food?",
  "What’s a song that always puts you in a good mood?",
  "If you had a superpower, what would it be?",
  "What's something you're grateful for today?",
  "What’s a place you’ve always wanted to visit?",
  "What's a challenge you overcame that made you stronger?",
  "What's your favorite quote or saying?",
  "If you could start any business, what would it be?",
  "What’s the most beautiful place you’ve ever seen?",
  "What's your favorite thing about your best friend?",
  "What's your morning routine like?",
  "What's a childhood dream you still think about?",
  "If you could swap lives with someone for a day, who would it be?",
  "What's your favorite way to spend a rainy day?",
  "What's a skill you’d like to learn this year?",
  "What's a decision you’re proud of?",
  "If you could change one thing about the world, what would it be?",
  "What's a tradition you want to start?",
  "What’s something you want to achieve before the year ends?",
  "If you could instantly know any language, which would it be?",
];
